
title: NAACL HLT 2015

description: >
  This is the website for NAACL HLT 2015, 
  taking place May 31–June 5 in Denver, Colorado, USA.

url: "http://naacl.org/naacl-hlt-2015"

markdown: kramdown

email:
  main: naacl2015@googlegroups.com
  webmaster: naacl2015-webmaster@googlegroups.com
  programchairs: naacl-2015-programchairs@googlegroups.com
  workshopchairs: naacl.acl.emnlp.w15@gmail.com
  tutorialchairs: nlp-tutorials-2015@googlegroups.com

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

social_media:
  - title: E-mail
    user: "naacl2015@googlegroups.com"
    url: "mailto:naacl2015@googlegroups.com"
    icon: img/email-icon-16.gif

  - title: Twitter
    user: "@NAACL2015"
    url: "http://twitter.com/NAACL2015"
    icon: img/twitter-icon-16.png

  # - title: Facebook
  #   user: "NAACL2015"
  #   url: "http://facebook.com/NAACL2015"
  #   icon: img/facebook-icon-16.gif
