
title: NAACL HLT 2015

description: >
  This is the website for NAACL HLT 2015, 
  taking place May 31–June 5 in Denver, Colorado, USA.

url: "http://naacl.org/2015"

markdown: kramdown

email:
  main: naacl2015@naacl.org
  webmaster: webmaster-naacl2015@naacl.org

exclude: ["README.md"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

social_media:
  - title: E-mail
    user: "naacl2015@naacl.org"
    url: "mailto:naacl2015@naacl.org"
    icon: img/email-icon-16.gif

  - title: Twitter
    user: "@NAACL2015"
    url: "http://twitter.com/NAACL2015"
    icon: img/twitter-icon-16.png

  # - title: Facebook
  #   user: "NAACL2015"
  #   url: "http://facebook.com/NAACL2015"
  #   icon: img/facebook-icon-16.gif
